package com.otn.webservice.com.inspur;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ResourceServiceService service = new ResourceServiceService();
 * ResourceServiceDelegate portType = service.getResourceServicePort();
 * portType.getChannel(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ResourceServiceService", targetNamespace = "http://inspur.com/", wsdlLocation = "http://10.114.223.15/resourceWebService/ResourceServicePort?wsdl")
public class ResourceServiceService extends Service {

	private final static URL RESOURCESERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.otn.webservice.com.inspur.ResourceServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.otn.webservice.com.inspur.ResourceServiceService.class.getResource(".");
			url = new URL(baseUrl,
					"http://10.114.223.15/resourceWebService/ResourceServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.114.223.15/resourceWebService/ResourceServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RESOURCESERVICESERVICE_WSDL_LOCATION = url;
	}

	public ResourceServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ResourceServiceService() {
		super(RESOURCESERVICESERVICE_WSDL_LOCATION, new QName(
				"http://inspur.com/", "ResourceServiceService"));
	}

	/**
	 * 
	 * @return returns ResourceServiceDelegate
	 */
	@WebEndpoint(name = "ResourceServicePort")
	public ResourceServiceDelegate getResourceServicePort() {
		return super.getPort(new QName("http://inspur.com/",
				"ResourceServicePort"), ResourceServiceDelegate.class);
	}

}
